version: '3'

services:

  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web

  redis:
    image: redis
    volumes:
      - redis_data:/data

  rabbitmq:
    container_name: "dockerize-rails-rabbitmq-1"
    image: rabbitmq:3.9-management
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypassword
    ports:
      # AMQP protocol port
      - '5672:5672'
      # HTTP management UI
      - '15672:15672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  memcached:
    image: memcached

  database:
    image: postgres
    env_file:
      - .env/development/database
    volumes:
      - db_data:/var/lib/postgresql/data

  mongo:
    image: mongo
    restart: always
    env_file:
      - .env/development/mongo
    volumes:
      - mongo_data:/data/db
      - mongo_configdb:/data/configdb

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .env/development/mongo-express

volumes:
  db_data:
  gem_cache:
  redis_data:
  rabbitmq_data:
  mongo_data:
  mongo_configdb: